### PR TITLE
add ollama quickstart pics

### PR DESCRIPTION
**Pull request by pengyb2001**
add ollama quickstart pics

### CODE REVIEW

**Comment by pengyb2001** [comment]
@shane-huang Please kindly review and merge the pics.

**Comment by jason-dai** [comment]
do not use bigdl in the path name

**Comment by pengyb2001** [comment]
> do not use bigdl in the path name

Sure, I'll update the pics later.

> do not use bigdl in the path name

updated

**Comment by shane-huang** [comment]
update index.rst as others do , e.g. https://github.com/bigdl-project/bigdl-project.github.io/pull/84/files#diff-455109ca9410eb7504d5da59cedf957e5da1cc6e3889c637ba6e64449978225a

**Comment by shane-huang** [comment]
merge now and I'll fix the image links

**Pull request merged**
